//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYMWebDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUSTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactUSTBL()
        {
            this.ContactUsReplyTBL = new HashSet<ContactUsReplyTBL>();
        }
    
        public int ContactID { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactIPAddress { get; set; }
        public string ContactMessage { get; set; }
        public Nullable<System.DateTime> DateOfMaking { get; set; }
        public Nullable<System.DateTime> DateOfLastUpdate { get; set; }
        public Nullable<int> EmployeeIDDLastUpdate { get; set; }
        public bool IsSeen { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactUsReplyTBL> ContactUsReplyTBL { get; set; }
    }
}
