//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYMWebDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeTBL()
        {
            this.CallingAPISAuthTBL = new HashSet<CallingAPISAuthTBL>();
            this.ContactUsReplyTBL = new HashSet<ContactUsReplyTBL>();
            this.EmployeeLoginTBL = new HashSet<EmployeeLoginTBL>();
            this.ExpenseRevenueTBL = new HashSet<ExpenseRevenueTBL>();
            this.ExpenseRevenueTBL1 = new HashSet<ExpenseRevenueTBL>();
            this.InternalChatTBL = new HashSet<InternalChatTBL>();
            this.ProjectTBL = new HashSet<ProjectTBL>();
            this.ProjectTBL1 = new HashSet<ProjectTBL>();
            this.RecoverPasswordTBL = new HashSet<RecoverPasswordTBL>();
        }
    
        public int EmployeeID { get; set; }
        public string AutoCode { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeeEmail { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeePhone1 { get; set; }
        public string EmployeePhone2 { get; set; }
        public string EmployeeAddress { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfHiring { get; set; }
        public Nullable<System.DateTime> DateOfeaving { get; set; }
        public string PassportOrIDNumber { get; set; }
        public string PassportORIDIMGURL { get; set; }
        public string ResumeFIleURL { get; set; }
        public string DocumentFileURL { get; set; }
        public Nullable<int> EmployeeTypeIDD { get; set; }
        public Nullable<int> MaritalStatusIDD { get; set; }
        public Nullable<int> GenderIDD { get; set; }
        public Nullable<int> EducationIDD { get; set; }
        public Nullable<int> ProfessionIDD { get; set; }
        public Nullable<int> SalaryIDD { get; set; }
        public Nullable<int> NationalityIDD { get; set; }
        public Nullable<int> CountryIDD { get; set; }
        public Nullable<int> GovernorateIDD { get; set; }
        public Nullable<int> CityIDD { get; set; }
        public Nullable<int> BranchIDD { get; set; }
        public Nullable<System.DateTime> DateOfMaking { get; set; }
        public Nullable<System.DateTime> DateOfLastUpdate { get; set; }
        public bool IsStopped { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual BranchTBL BranchTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallingAPISAuthTBL> CallingAPISAuthTBL { get; set; }
        public virtual CityTBL CityTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactUsReplyTBL> ContactUsReplyTBL { get; set; }
        public virtual CountryTBL CountryTBL { get; set; }
        public virtual EducationTBL EducationTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLoginTBL> EmployeeLoginTBL { get; set; }
        public virtual EmployeeTypeTBL EmployeeTypeTBL { get; set; }
        public virtual GenderTBL GenderTBL { get; set; }
        public virtual GovernorateTBL GovernorateTBL { get; set; }
        public virtual MaritalStatusTBL MaritalStatusTBL { get; set; }
        public virtual NationalityTBL NationalityTBL { get; set; }
        public virtual ProfessionTBL ProfessionTBL { get; set; }
        public virtual SalaryTBL SalaryTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseRevenueTBL> ExpenseRevenueTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseRevenueTBL> ExpenseRevenueTBL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalChatTBL> InternalChatTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTBL> ProjectTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTBL> ProjectTBL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoverPasswordTBL> RecoverPasswordTBL { get; set; }
    }
}
