//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYMWebDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseRevenueTypeTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenseRevenueTypeTBL()
        {
            this.ExpenseRevenueTBL = new HashSet<ExpenseRevenueTBL>();
        }
    
        public int ExpenseRevenueTypeID { get; set; }
        public string ExpenseRevenueName { get; set; }
        public string ExpenseRevenueNotes { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseRevenueTBL> ExpenseRevenueTBL { get; set; }
    }
}
