//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYMWebDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseRevenueTBL
    {
        public int ExpenseRevenueID { get; set; }
        public string AutoCode { get; set; }
        public Nullable<int> ExpenseRevenueTypeIDD { get; set; }
        public Nullable<int> ResourceFromIDD { get; set; }
        public Nullable<int> ResourceToIDD { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> ClientIDD { get; set; }
        public Nullable<int> EmployeeIDD { get; set; }
        public Nullable<int> ProjectIDD { get; set; }
        public bool Expense0_Revenue1 { get; set; }
        public string InvoiceFileURL { get; set; }
        public string ExpenseRevenueNotes { get; set; }
        public Nullable<System.DateTime> DateOfMaking { get; set; }
        public Nullable<System.DateTime> DateOfLastUpdate { get; set; }
        public Nullable<int> EmployeeIDDLastUpdate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ClientTBL ClientTBL { get; set; }
        public virtual EmployeeTBL EmployeeTBL { get; set; }
        public virtual EmployeeTBL EmployeeTBL1 { get; set; }
        public virtual ExpenseRevenueTypeTBL ExpenseRevenueTypeTBL { get; set; }
        public virtual ProjectTBL ProjectTBL { get; set; }
        public virtual ResourceTBL ResourceTBL { get; set; }
        public virtual ResourceTBL ResourceTBL1 { get; set; }
    }
}
