//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYMWebDevelopment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AYMCOMPDataContext : DbContext
    {
        public AYMCOMPDataContext()
            : base("name=AYMCOMPDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BranchTBL> BranchTBL { get; set; }
        public virtual DbSet<CallingAPISAuthTBL> CallingAPISAuthTBL { get; set; }
        public virtual DbSet<CareerTBL> CareerTBL { get; set; }
        public virtual DbSet<CityTBL> CityTBL { get; set; }
        public virtual DbSet<ClientTBL> ClientTBL { get; set; }
        public virtual DbSet<ContactUsReplyTBL> ContactUsReplyTBL { get; set; }
        public virtual DbSet<ContactUSTBL> ContactUSTBL { get; set; }
        public virtual DbSet<CountryTBL> CountryTBL { get; set; }
        public virtual DbSet<EducationTBL> EducationTBL { get; set; }
        public virtual DbSet<EmployeeLoginTBL> EmployeeLoginTBL { get; set; }
        public virtual DbSet<EmployeeTBL> EmployeeTBL { get; set; }
        public virtual DbSet<EmployeeTypeTBL> EmployeeTypeTBL { get; set; }
        public virtual DbSet<ExpenseRevenueTBL> ExpenseRevenueTBL { get; set; }
        public virtual DbSet<ExpenseRevenueTypeTBL> ExpenseRevenueTypeTBL { get; set; }
        public virtual DbSet<GenderTBL> GenderTBL { get; set; }
        public virtual DbSet<GovernorateTBL> GovernorateTBL { get; set; }
        public virtual DbSet<InternalChatTBL> InternalChatTBL { get; set; }
        public virtual DbSet<MaritalStatusTBL> MaritalStatusTBL { get; set; }
        public virtual DbSet<NationalityTBL> NationalityTBL { get; set; }
        public virtual DbSet<ProfessionTBL> ProfessionTBL { get; set; }
        public virtual DbSet<ProjectPriceTBL> ProjectPriceTBL { get; set; }
        public virtual DbSet<ProjectStatusTBL> ProjectStatusTBL { get; set; }
        public virtual DbSet<ProjectTBL> ProjectTBL { get; set; }
        public virtual DbSet<ProjectTypeTBL> ProjectTypeTBL { get; set; }
        public virtual DbSet<RecoverPasswordTBL> RecoverPasswordTBL { get; set; }
        public virtual DbSet<ResourceTBL> ResourceTBL { get; set; }
        public virtual DbSet<SalaryTBL> SalaryTBL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
