//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AYMWebDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTBL()
        {
            this.ExpenseRevenueTBL = new HashSet<ExpenseRevenueTBL>();
        }
    
        public int ProjectID { get; set; }
        public string AutoCode { get; set; }
        public Nullable<int> ProjectStatusIDD { get; set; }
        public string ProjectRequirements { get; set; }
        public Nullable<int> ProjectPriceIDD { get; set; }
        public Nullable<int> ProjectTypeIDD { get; set; }
        public string ProjectNotes { get; set; }
        public Nullable<int> EmployeeIDDManager { get; set; }
        public Nullable<int> ClientIDD { get; set; }
        public string ProjectDetailsFileURL { get; set; }
        public Nullable<System.DateTime> DateOfMaking { get; set; }
        public Nullable<System.DateTime> DateOfLastUpdate { get; set; }
        public Nullable<int> EmployeeIDDLastUpdate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ClientTBL ClientTBL { get; set; }
        public virtual EmployeeTBL EmployeeTBL { get; set; }
        public virtual EmployeeTBL EmployeeTBL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseRevenueTBL> ExpenseRevenueTBL { get; set; }
        public virtual ProjectPriceTBL ProjectPriceTBL { get; set; }
        public virtual ProjectStatusTBL ProjectStatusTBL { get; set; }
        public virtual ProjectTypeTBL ProjectTypeTBL { get; set; }
    }
}
